apiVersion: apps/v1
kind: Deployment
metadata:
  name: demucs-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demucs-rest
  template:
    metadata:
      labels:
        app: demucs-rest
    spec:
      containers:
        - name: demucs-rest
          image: gaka4787/demucs-rest:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: REDISTOGO_URL
              value: "redis"
            - name: REDISTOGO_PORT
              value: "6379"
            - name: MINIO_HOST
              value: "minio:9000"